language: generic
sudo: required
services:
  - docker

before_install:
  - docker image build -t suriya0304/docker-react -f Dockerfile.dev

script:
  - docker container run -e CI=true suriya0304/docker-react npm run test
