version: "3"
services:
  web:
    stdin_open: true
    environment:
      - WATCHPACK_POLLING=true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:3000"
    volumes:
      - /pract/node_modules
      - .:/pract
  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /pract/node_modules
      - .:/pract
    command: ["npm", "run", "test"]
